name: flutter_camera_app
description: Entertainment And Chill

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  deepar_flutter: ^0.0.3
  camera: ^0.10.0+4
  open_file: ^3.2.1
  provider: ^6.0.4
  flame: ^1.5.0
  hive: ^2.2.3
  flame_audio: ^1.3.3
  path_provider: ^2.0.11
  flutter_spinkit: ^5.1.0
  flutter_phoenix: ^1.1.0
  animated_splash_screen: ^1.3.0
  flutter_carousel_slider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.0
  build_runner: 2.3.2
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/images/global/app_icon.png"
  adaptive_icon_foreground: "assets/images/global/app_icon_512.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/ar/
    - assets/images/dino/enemies/angryPig/
    - assets/images/dino/enemies/bat/
    - assets/images/dino/enemies/rino/
    - assets/images/dino/parallax/
    - assets/images/dino/player/dinoGif/
    - assets/images/dino/player/dinoSprites/
    - assets/images/spacescape/
    - assets/audio/dino/
    - assets/audio/spacescape/
    - assets/effects/ar/
    - assets/images/global/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/dino/Audiowide-Regular.ttf
    - family: StarJedi
      fonts:
        - asset: assets/fonts/2048/starjedi.ttf
    - family: BungeInline
      fonts:
        - asset: assets/fonts/spacescape/BungeeInline-Regular.ttf
